### ISSUE TITLE
Wrong URL is used for group library entries

### ISSUE THREAD

**Issue by cinemakinoeye** [frthjf/obsidian-zotero-sync-client#10]
When working with a Zotero Library that has group libraries, the plug-in uses this URL format:
zotero://select/library/items/PDT4LQ75

But to access the item in a group library, it should be: 
zotero://select/groups/4763555/items/PDT4LQ75

**Comment by frthjf** [comment]
Thanks for reporting, this should be fixed in [v1.3.4](https://github.com/frthjf/obsidian-zotero-sync-client/releases/tag/1.3.4).
