### ISSUE TITLE
Access the group library name?

### ISSUE THREAD

**Issue by cinemakinoeye** [frthjf/obsidian-zotero-sync-client#11]
Is it possible to access the group library name from the Template? 

It's great to have the collection name; I would also like to show the group library name.

If the variable is not exposed, please consider making it accessible to the Template.

**Comment by frthjf** [comment]
You can access it via `$library` which contains the following fields:
```typescript
{
    type: 'group' | 'user';
    prefix: string;
    name: string;
    version?: number;
}
```

For example, `n += 'My library: ' + $library.name` will add the name to the template.
