### ISSUE TITLE
Library doesn't load / no way to configure folder

### ISSUE THREAD

**Issue by huachuman** [frthjf/obsidian-zotero-sync-client#2]
Am I missing something or should there be a field to configure the folder where the notes go? I connected my API and it says it finished syncing but the settings shows me no files to test the templates with and I can't find any of the references in my vault.

**Comment by huachuman** [comment]
Nevermind... it just started working. I don't know what did it but since I posted it the problem has resolved itself. A restart was not good enough at first but I wonder if it just took a really long time because my library has over 20k items.

**Comment by frthjf** [comment]
Hi @huachuman, 

Yes, it may have been a delay. The way it works is that plugin syncs all data into a JSON file first and only then proceeds to generate the corresponding markdown files according to the specified template function.

You can customize the output folder by changing the return value of the template function in the plugin settings, see screenshot below:

![image](https://github.com/frthjf/obsidian-zotero-sync-client/assets/5411942/00af7814-1696-4d23-a0b9-640b0394e8ab)

It will show you a preview of the file structure in the list on the right-hand side. Once you are happy with it, you can hit the 'Apply' button to update your vault.

I am going to close this for now, but let me know if you encounter any other issues.
