### ISSUE TITLE
Template modification : zotero tags

### ISSUE THREAD

**Issue by marckcolina** [frthjf/obsidian-zotero-sync-client#3]
Hello ! I have tried to modify the template so the tags could be imported as the notes.

even if the number of tags come ok (i had 7 tags in a document and the number of references were ok in obsidian) the tags came empty, showing only « object » as reference for each… have you tried this before ? Any ideas ? Thanks !

**Comment by frthjf** [comment]
Hi @marckcolina! It might be that you are trying to print the entire tag object which consists of the tag name and the type. You should be able to map over them to extract the names, for example, you might try something like this:

```js
n += '\n\nTags: ' + data.tags.map(t => '#' + t.tag).join(', ') + '\n';
```

If that does not work, could you share the code example and data?

**Comment by marckcolina** [comment]
Hi frthjf. That worked perfectly. 

I've tried something a lot more complicated, even if it worked at the end, but not pretty at all. It was something like that :

if (data.tags && data.tags.length == 1) {
n += '#'+data.tags[0]['tag'];
}

and to repeat for number of tags...

Have to say, that i know nothing at all in java language, i'm a social sciences researcher !

thank you very much

**Comment by marckcolina** [comment]
would you kindly help me with the necessary code to import the abstract as well ? Thanks in advance...

**Comment by frthjf** [comment]
Fair enough!

You can find out how to access the data by switching to the `View JSON data` option (see screenshot below).

For example, for the abstract you'll likely want `abstractNote`, so something like this:
```js
n += '\n\nAbstract: ' + data.abstractNote + '\n\n'
```

![image](https://github.com/frthjf/obsidian-zotero-sync-client/assets/5411942/f3f85a14-a403-49a0-bb84-85366c3e8b0f)

**Comment by marckcolina** [comment]
Dear frthjf, sorry to disturb you again. Do you know why some references from the same author don't get imported into Obsidian ? I'm having this issue with several articles. For exemple, in these images you'll see that i have two publications from "Motta" in Zotero, but in obsidian i only get one of them... Thank you in advance !

![Capture d’écran 2023-10-30 à 16 33 26](https://github.com/frthjf/obsidian-zotero-sync-client/assets/148648580/7644f477-4dea-42e1-af92-6a7298e0348f)

![Capture d’écran 2023-10-30 à 16 33 14](https://github.com/frthjf/obsidian-zotero-sync-client/assets/148648580/413d5825-a0fc-4d3b-ad2a-94c52d3b8c8f)

**Comment by frthjf** [comment]
I am not sure, do both articles appear in the plugin settings?

**Comment by frthjf** [comment]
I've added the reference, but I am afraid I can't reproduce the issue as it appears in my list.

One thing you could try is to write `return data.key;` above everything else in the top-left editor and check if the key `JWNW5RMY` and `45P2GC8J` are part of the list. If they are, then check the JSON view to see if `data.creators` field is empty. The `if (data.creators) {` means that any entries with a missing `data.creators` are omitted.

**Comment by marckcolina** [comment]
Thanks ! Well, i've done all that. I found the issue. If the creator is not an "author" and at the top of the list in Zotero, the plugin omite it (in this case, first where the editors than the author). 

I changed that in zotero and the reference came effectively into Obsidian... 

![Capture d’écran 2023-10-30 à 18 26 46](https://github.com/frthjf/obsidian-zotero-sync-client/assets/148648580/f6a8dd12-f76d-490a-aa84-8fe0721d26d5)

Thanks again !

**Comment by frthjf** [comment]
Ok great, glad you've found the issue.

**Comment by marckcolina** [comment]
Instead, there's another one. Institutional Authors are not imported (those with no difference between first and last name)... But i'll change them to normal author with no first name, that will fix the issue as well. 

![Capture d’écran 2023-10-30 à 18 42 18](https://github.com/frthjf/obsidian-zotero-sync-client/assets/148648580/1a92779e-5c5d-478b-9fcf-d04804aacd31)
