### ISSUE TITLE
Year from non-standard date format

### ISSUE THREAD

**Issue by olivierroymd** [frthjf/obsidian-zotero-sync-client#4]
Thanks for this useful plugin.
I have multiple items in my Zotero library that have the Date format m/yyyy (eg. 4/2018). The current let `year = new Date(data.date).getFullYear();` returns NaN in this case. How can I get the year from that non-standard date format?

**Comment by frthjf** [comment]
Hi @olivierroymd ,

I haven't tested it, but how about something like this? 

```js
let dateObj;

if (data.date.includes('/')) {
  let parts = data.date.split('/');
  if (parts.length === 2) {
      let dateWithDay = parts[0] + '/01/' + parts[1];
      dateObj = new Date(dateWithDay);
  }
} else {
  dateObj = new Date(data.date);
}

let year = dateObj ? dateObj.getFullYear() : 'invalid';
```

**Comment by olivierroymd** [comment]
@frthjf 
Thanks, it works. Pardon my laziness on account on not knowing javascript at all!
