### ISSUE TITLE
Expose other items and collections during template generation

### ISSUE THREAD

**Issue by Wang-Zhongwei** [frthjf/obsidian-zotero-sync-client#5]
Hello, 

I am just wondering can you guys also sync tags and collections from Zotero. Since a paper can belong to multiple collections, maybe you can make collections as a multi-select field. I am not sure if these features are provided in the zotero-sync github repo you have been using. But it would be really awesome if you could colorize papers in the graph view based on collections and article tags.

**Comment by frthjf** [comment]
Hi @Wang-Zhongwei, 

Yes, both collections and tags are already supported. The data is available under the `data.tags` and `data.collections`/`data.super_collections` field. See #3 on how you could modify the default template to include the information in your notes.

**Comment by Wang-Zhongwei** [comment]
Thank you for your reply! But I encountered a problem when I tried to inserting collections in my template. But when I use `data.collections.map(item => console.log(item)).join('\n')`. It actually just prints out the hash of my collections like `ZRRU95U7` in the console without actual names. Seems like `data.collections` doesn't have any properties at all. Then how to get access to the name of my collections? 
<img width="546" alt="Screenshot 2023-12-04 at 16 26 35" src="https://github.com/frthjf/obsidian-zotero-sync-client/assets/55232457/e38e6bd8-77ca-4272-9cb3-164385514d14">

**Comment by frthjf** [comment]
Ah, I see; currently, the information is there but it's not exposed globally through the `data` object. I could look into making this available. In the meantime, if you like to prepare a PR, I think all it takes [here](https://github.com/frthjf/obsidian-zotero-sync-client/blob/d7ba3ef806f7fcf4e7b5fed8a2144fb8ae7321c6/main.ts#L342C24-L342C24) is making the `data` map available to each element.
