### ISSUE TITLE
Authentication fails when entering Zotero API Key

### ISSUE THREAD

**Issue by artofbeinghuman** [frthjf/obsidian-zotero-sync-client#6]
When trying to establish first connection I get this authentication error, after pasting in my key:
<img width="277" alt="image" src="https://github.com/frthjf/obsidian-zotero-sync-client/assets/19737739/b9214c9f-1f37-46ec-95fe-66a04d9422b4">

This is how I generated my api key:
<img width="570" alt="image" src="https://github.com/frthjf/obsidian-zotero-sync-client/assets/19737739/479603d6-5150-4138-aa5f-61225afe74ae">
Resulting Key: majV0Jc3TIpTr1byxWxf1ld1  
(Key since deleted, so I'm not exposing anything here)

What am I doing wrong?
macOS 13, Obsidian v1.4.16, Zotero v6.0.30

**Comment by frthjf** [comment]
Hi @artofbeinghuman,

Not sure what's wrong there. Have you tried with `Allow note access` and `Read only` group permissions enabled? 

Could you open the developer tools in obsidian to see if there are more error details in the console.

Thanks!

**Comment by artofbeinghuman** [comment]
Hi @frthjf, thanks for your help. I tried again today and now it works, not sure what's different, but thanks anyway :)
