### ISSUE TITLE
Working with group libraries

### ISSUE THREAD

**Issue by purierca** [frthjf/obsidian-zotero-sync-client#7]
Hi!
Great plugin thanks a lot.
I'm working a lot with group libraries in Zotero and I've created an API key that authorizes Read/Write on Zotero groups, however I only get my personal library in Obsidian, is that on purpose or on your roadmap? 
Thanks alot

**Comment by frthjf** [comment]
Hi @purierca,

Thanks for reporting, I'll have to look into this. It should be working (see support for it [here](https://github.com/frthjf/obsidian-zotero-sync-client/blob/main/main.ts#L876)), but I've never tested it so there is a good chance it's not working properly.

I probably won't get around to working on this immediately, so I welcome PRs in the meantime.

**Comment by frthjf** [comment]
After a little digging, it looks like this is an [upstream issue](https://github.com/retorquere/zotero-sync/issues/16). However, there is a workaround:
1. Go to Zotero.org to [manage your keys](https://www.zotero.org/settings/keys)
2. Click `Edit key`
3. Go to `Specific Groups` and enable `Per Group Permissions`
4. Set the libraries you like to sync to `Read Only`

This should make the group libraries appear; let me know if this does not work.

In any case, I'll keep this open until we can get it properly resolved.
